# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 22:51
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxp_v1', '0002_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/home/ubuntu/Django/django_v1/protected'), upload_to='download'),
        ),
    ]
